<?php
/**
 * Created by PhpStorm.
 * User: usama
 * Date: 5/10/18
 * Time: 5:55 PM
 */

return [
    [
        'name_ar' => 'الكويت',
        'name_en' => 'kuwait',
        "calling_code" => "965",
        'currency_ar' => "دينار كويتي",
        'currency_en' => 'Kuwait Dinar',
        "currency_symbol_en" => "KWD",
        "currency_symbol_ar" => "د.ك",
        'country_code' => 'KW',
        'exchange_rate' => 1,
        'governates' => [
            [
                'name_ar' => 'جهراء',
                'name_en' => 'Jahra',
                'areas' => [
                    ['name_en' => 'Al Sulaibiya Industrial 1', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Al Sulaibiya Industrial 2', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Amgarah Industrial Area', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Jahra', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Naeem', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Naseem', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Oyoun', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Qasr', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Saad Al Abdullah', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Sulaibiya', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Taima', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Waha', 'name_ar' => 'اسم المنطقة'],
                ]
            ],
            [
                'name_ar' => 'أحمدي',
                'name_en' => 'Ahmadi',
                'areas' => [
                    ['name_en' => 'Abu Halifa', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Ahmadi', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Al Khiran', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Al Wafrah', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Al-Julaia', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Al-Nuwaiseeb', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Al-Riqqa', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Ali Sabah Al Salem', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Assabahiyah', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Bnaider', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Dahar', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Eqaila', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Fahad Al Ahmad', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Fahaheel', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Fintas', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Hadiya', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Jaber Al Ali', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Mahboula', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Mangaf', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Sabah Al Ahmad', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Shalayhat Al Dubaiya', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Shalayhat Mina Abdullah', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Shuaiba Block 1', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'West Industrial Shuaiba', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Zour', 'name_ar' => 'اسم المنطقة'],
                ]
            ],
            [
                'name_ar' => 'مبارك الكبير',
                'name_en' => 'Mubarak Al Kabir',
                'areas' => [
                    ['name_en' => 'Abu Al Hasaniya', 'name_ar' => 'name_ar'],
                    ['name_en' => 'Abu Fatira', 'name_ar' => 'name_ar'],
                    ['name_en' => 'Adan', 'name_ar' => 'name_ar'],
                    ['name_en' => 'Al-Masayel', 'name_ar' => 'name_ar'],
                    ['name_en' => 'Coast Strip B', 'name_ar' => 'name_ar'],
                    ['name_en' => 'Fnaitees', 'name_ar' => 'name_ar'],
                    ['name_en' => 'Messila', 'name_ar' => 'name_ar'],
                    ['name_en' => 'Mubarak Al Kabeer', 'name_ar' => 'name_ar'],
                    ['name_en' => 'Qurain', 'name_ar' => 'name_ar'],
                    ['name_en' => 'Qusor', 'name_ar' => 'name_ar'],
                    ['name_en' => 'Sabah Al Salem', 'name_ar' => 'name_ar'],
                    ['name_en' => 'Sabhan Industrial Area', 'name_ar' => 'name_ar'],
                    ['name_en' => 'South Wista', 'name_ar' => 'name_ar'],
                    ['name_en' => 'West Abu Fatira Small Industrial', 'name_ar' => 'name_ar'],
                    ['name_en' => 'Wista', 'name_ar' => 'name_ar'],
                ]
            ],
            [
                'name_ar' => 'حولي',
                'name_en' => 'Hawally',
                'areas' => [
                    ['name_en' => 'Al-Bidea', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Al-Siddeeq', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Anjafa', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Bayan', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Hateen', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Hawally', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Jabriya', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Maidan Hawally', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Mishref', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Mubarak Al-Abdullah', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Rumaithiya', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Salam', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Salmiya', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Salwa', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Shaab', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Shuhada', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Zahra', 'name_ar' => 'اسم المنطقة'],
                ]
            ],
            [
                'name_ar' => 'فروانية',
                'name_en' => 'Farwaniya',
                'areas' => [
                    ['name_en' => 'Abbasiya', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Abdullah Al Mubarak Al Sabah', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Abraq Khaitan', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Airport', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Al-Dajeej', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Al-Shadadiya', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Andalous', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Ardiya', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Ardiya Small Industrial', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Ardiya Storage Zone', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Doha', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Farwaniya', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Firdous', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Ishbiliya', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Jeleeb Al-Shuyoukh', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Khaitan', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Kuwait International Airport', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Omariya', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Rabia', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Rai', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Rehab', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Rigai', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Sabah Al Nasser', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'Sheikh Saad Aviation Terminal', 'name_ar' => 'اسم المنطقة'],
                    ['name_en' => 'South Khaitan - Exhibits', 'name_ar' => 'اسم المنطقة'],
                ]
            ],
            [
                'name_en' => 'Kuwait City',
                'name_ar' => 'مدينة الكويت',
                'areas' => [
                    [
                        ['name_en' => 'Daiya', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Dasma', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Dasman', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Faiha', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Granada', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Jaber Al Ahmad', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Jibla', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Kaifan', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Khaldiya', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Kuwait City', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Kuwait Free Trade Zone', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Mansouriya', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Mirqab', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Mubarekiya Camps and Collages', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Nahdha', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'North West Al-Sulaibikhat', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Nuzha', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Qadsiya', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Qairawan', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Qortuba', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Rawda', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Salhiya', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Shamiya', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Sharq', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Shuwaikh Administrative', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Shuwaikh Industrial', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Shuwaikh Industrial 1', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Shuwaikh Industrial 2', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Shuwaikh Industrial 3', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Shuwaikh Residential', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Sulaibikhat', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Surra', 'name_ar' => 'اسم المنطقة'],
                        ['name_en' => 'Yarmouk', 'name_ar' => 'اسم المنطقة'],
                    ]
                ]
            ]
        ],
    ],
    [
        'name_ar' => 'السعودية',
        'name_en' => 'Saudi Arabia',
        "calling_code" => "966",
        'currency_ar' => "ريال سعودي",
        'currency_en' => 'Ryal Saudi',
        "currency_symbol_en" => "SR",
        "currency_symbol_ar" => "ر.س",
        'country_code' => 'SAR',
        'exchange_rate' => 0.4,
        'governates' => []
    ],
    [
        'name_ar' => 'الإمارات',
        'name_en' => 'United Arab Emirates',
        "calling_code" => "967",
        'currency_ar' => "درهم إماراتي",
        'currency_en' => 'AED',
        "currency_symbol_en" => "AED",
        "currency_symbol_ar" => "د.إ",
        'country_code' => 'AED',
        'exchange_rate' => 0.7,
        'governates' => []
    ],
];